### ISSUE TITLE
Does not work on Haiku 64 bit nightly

### ISSUE THREAD

**Issue by Brunobasta** [HaikuArchives/PecoRename#66] opened 2021-11-18 17:45 UTC
does crash when opened as Add-on or when choosing files.
http://0x0.st/-R68.report

**Comment by humdingerb** [comment] 2021-11-18 18:35
Duplicate of #64.
There's PR #65 that would fix it, but I'm not sure it's the right fix...

**Closed by humdingerb** 2021-11-18 18:35 UTC
