### ISSUE TITLE
PecoRename doesn't respond 

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/PecoRename#8] opened 2016-12-20 11:33 UTC
When running PecoRename Window in background and doing some task PecoRename goes stubborn mode and does't respond . This happened to me when I was trying to change my font size from 24 to default .

**Comment by humdingerb** [comment] 2016-12-20 12:51
Is this reproducible? If so, please make a bullet list that describes everything step-by-step. Simply changing font size to 24 in Appearance prefs while the PecoRename window is open doesn't do it for me, and I can't find a PecoRename operation that would take long enough to keep it busy while I'm changing font size.

**Comment by humdingerb** [comment] 2016-12-20 13:02
Might be a duplicate of #5 .

**Comment by vanishakesswani** [comment] 2016-12-20 13:04
Yes.

- Change font size to 24 in Appearance .
- Restart the system
- Open PecoRename
- Click default in Appearance 
and your PecoRename won't respond .

**Comment by humdingerb** [comment] 2016-12-20 13:34
Thanks! No restart needed BTW. It really does appear to be a duplicate of #5 .

**Closed by humdingerb** 2016-12-20 13:34 UTC
Labels: duplicate
